// ==========================================================================
// CONTROL MAESTRO DE BASE DE DATOS LOCAL - INFINIX BEAST MODE (RESPALDO COMPLETO)
// ==========================================================================

// 1. SISTEMA DE CREDENCIALES POR ROL (HASHES LOCALES SIMULADOS)
const baseDatosAsesores = {
    "ADMIN": { pass: "Jgmz242520", nombre: "Jershon (Administrador Supremo)", rol: "admin" },
    "GERENTE": { pass: "gerencia2026", nombre: "Gerencia Comercial", rol: "gerente" },
    "SUPERVISOR": { pass: "supervisor2026", nombre: "Supervisión de Puntos", rol: "supervisor" },
    "TRAINER": { pass: "trainer2026", nombre: "Trainer (Formador de Marca)", rol: "trainer" },
    "ASESOR": { pass: "ventas2026", nombre: "Asesor de Ventas Elite", rol: "asesor" }
};

// 2. BASE DE DATOS COMPLETA DE DISPOSITIVOS INFINIX
const infinixDatabase = {
    'smart-20': {
        name: "Infinix Smart 20", image: "./Smart_20.png", emoji: "📱", screen: "6.6\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 120,
        processor: "Helio G81", ram: "4 GB", storage: "128 GB", battery: "5200 mAh", charge: "15W",
        durability: "Protección IP53 contra salpicaduras", camera: "Trasera: 8 Mpx / Frontal: 8 Mpx", color: "Negro Cristal", red: "4G",
        focal: "f/2.0", sensor: "OmniVision OV08A", cpu_cores: "8 Núcleos (2x Cortex-A75 + 6x Cortex-A55)", ufs: "eMMC 5.1", giroscopio: "Virtual (Software)", refrigeracion: "Disipación pasiva estándar",
        highlights: ["✔ Tasa de refresco ultra fluida de 120Hz en gama Smart.", "✔ Batería masiva de 5200 mAh superior al estándar tradicional.", "✔ Procesamiento optimizado con Chipset Helio G81 de gran rendimiento diario."]
    },
    'hot-60i': {
        name: "Infinix Hot 60i", image: "./Hot_60.png", emoji: "🔥", screen: "6.7\" IPS LCD HD+ (120 Hz)", screentype: "IPS LCD", hz: 120,
        processor: "Helio G81 Ultimate", ram: "4/8 GB", storage: "128/256 GB", battery: "5160 mAh", charge: "45W",
        durability: "IP64, resiste caídas 1.5m", camera: "Trasera: 50 Mpx / Frontal: 8 Mpx", color: "Diseño ultradelgado 7.7mm", red: "4G",
        focal: "f/1.6", sensor: "Hynix Hi-5021", cpu_cores: "8 Núcleos @ 2.0 GHz", ufs: "UFS 2.2", giroscopio: "Virtual (Software)", refrigeracion: "Láminas de grafito de alta densidad",
        highlights: ["✔ Chasis extremadamente delgado de solo 7.7mm de grosor y gran resistencia a caídas de 1.5 metros.", "✔ Extraordinaria carga de 45W (50% en 24min) sumada a carga inversa de 10W.", "✔ Infinix AI integrada, con asistente Folax, IR Blaster para electrodomésticos y altavoces duales DTS."]
    },
    'hot-70': {
        name: "Infinix HOT 70", image: "./Hot_70.png", emoji: "👑", screen: "6.78\" IPS LCD HD+ (120 Hz)", screentype: "IPS LCD", hz: 120,
        processor: "Helio G100 Ultimate", ram: "4 GB", storage: "256 GB", battery: "5600 mAh", charge: "45 W",
        durability: "IP54/IP65 - SGS Militar 5★ (Blindado Oficial)", camera: "Trasera: 50 Mpx / Frontal: 8 Mpx", color: "Thermo Orange (Cambia al tacto)", red: "4G",
        focal: "f/1.6 Ultra Apertura", sensor: "Sony IMX582", cpu_cores: "8 Núcleos (2x Cortex-A76 @ 2.2GHz)", ufs: "UFS 2.2 Avanzado", giroscopio: "Físico (Hardware)", refrigeracion: "Sistema de disipación multicapa de siliconato térmico",
        highlights: ["✔ Único modelo certificado con SGS Grado Militar 5 Estrellas contra impactos extremos.", "✔ Innovador color Thermo Orange que cambia dinámicamente con la temperatura corporal.", "✔ Increíble carga súper rápida de 45 W con batería de 5600 mAh."]
    },
    'hot-60-pro': {
        name: "Infinix Hot 60 Pro+", image: "./Note_60_Pro.png", emoji: "⚡", screen: "6.78\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 144,
        processor: "Helio G200 Ultimate", ram: "8 GB", storage: "256 GB", battery: "5160 mAh", charge: "45 W",
        durability: "Protección contra salpicaduras avanzada", camera: "Trasera: 50 Mpx / Frontal: 13 Mpx", color: "Azul Eléctrico", red: "4G",
        focal: "f/1.7", sensor: "Samsung ISOCELL JN1", cpu_cores: "8 Núcleos Mediatek Gaming", ufs: "UFS 2.2 Dual Channel", giroscopio: "Físico", refrigeracion: "Cámara de vapor integrada",
        highlights: ["✔ Brutal procesador Helio G200 Ultimate optimizado para gaming y renderizado.", "✔ Generosa memoria RAM física de 8 GB para una multitarea sin cierres.", "✔ Potente cámara frontal de 13 Mpx para selfies de alta definición."]
    },
    'note-edge': {
        name: "Infinix Note Edge", image: "./Note_Edge.png", emoji: "📱", screen: "6.78\" AMOLED Cuva (120 Hz)", screentype: "AMOLED Curva", hz: 120,
        processor: "Dimensity 7100", ram: "8 GB", storage: "256 GB", battery: "6150 mAh", charge: "45 W",
        durability: "IP64 protección de grado avanzado", camera: "Trasera: 50 Mpx / Frontal: 13 Mpx", color: "Verde Esmeralda", red: "5G",
        focal: "f/1.8", sensor: "Sony IMX686 Premium", cpu_cores: "8 Núcleos (2x Cortex-A78 @ 2.4GHz + 6x Cortex-A55)", ufs: "UFS 3.1 High Speed", giroscopio: "Físico", refrigeracion: "Cámara de vapor VC líquida de 3000mm²",
        highlights: ["✔ Elegante pantalla curva AMOLED premium con colores cinemáticos de alta inmersión.", "✔ Titán de energía: 6150 mAh con soporte de red ultra veloz 5G.", "✔ Cámara de alta fidelidad de 50 Mpx combinada con selfie de 13 Mpx."]
    },
    'note-60': {
        name: "Infinix Note 60", image: "./Note_60.png", emoji: "🛡️", screen: "6.78\" AMOLED (120 Hz)", screentype: "AMOLED", hz: 144,
        processor: "Dimensity 7400", ram: "8 GB", storage: "256 GB", battery: "6150 mAh", charge: "45W",
        durability: "IP64 protección de alta resistencia", camera: "Trasera: 50 Mpx / Frontal: 13 Mpx", color: "Gris Titanio", red: "5G",
        focal: "f/1.75", sensor: "Sony LYTIA LYT-600", cpu_cores: "8 Núcleos @ 2.5 GHz 4nm", ufs: "UFS 3.1", giroscopio: "Físico", refrigeracion: "Cámara de vapor VC combinada con grafito",
        highlights: ["✔ Potente procesador Dimensity 7400 para velocidad extrema bajo redes 5G.", "✔ Enorme batería de 6150 mAh con tecnología de carga optimizada de 45W.", "✔ Pantalla AMOLED brillante y vibrante para consumo multimedia."]
    },
    'note-60-pro': {
        name: "Infinix Note 60 PRO", image: "./Note_60_Pro.png", emoji: "🚀", screen: "6.78\" AMOLED (120 Hz)", screentype: "AMOLED Premium", hz: 144,
        processor: "Snapdragon 7s Gen 4", ram: "8 GB", storage: "256 GB", battery: "6000 mAh", charge: "90W",
        durability: "Protección IP64 avanzada", camera: "Trasera: 50 Mpx / Frontal: 13 Mpx", color: "Plata Estelar", red: "5G",
        focal: "f/1.65 OIS Estabilizado", sensor: "Sony IMX890", cpu_cores: "8 Núcleos Qualcomm Elite (4x Cortex-A78 + 4x Cortex-A55)", ufs: "UFS 3.1 Super Speed", giroscopio: "Físico Giroscópico de Precisión", refrigeracion: "Cámara de vapor líquida VC 3D Gaming",
        highlights: ["✔ Carga súper sónica de 90W: 0 a 100% en tiempo récord.", "✔ Chipset insignia Snapdragon 7s Gen 4 de alta eficiencia energética.", "✔ Batería titánica de 6000 mAh que redefine la duración extrema en 5G."]
    },
    'note-60-ultra': {
        name: "Infinix Note 60 Ultra", image: "./Note_60_ultra.png", emoji: "🛸", screen: "6.78\" AMOLED Curva 1.5K (144 Hz)", screentype: "AMOLED", hz: 144,
        processor: "Dimensity 8400 Ultimate", ram: "12 GB", storage: "256/512 GB", battery: "7000 mAh", charge: "100W",
        durability: "Gorilla Glass Victus, IP64, 7.9mm", camera: "Trasera: 200 Mpx / Frontal: 32 Mpx", color: "Active Halo & Diseño Pininfarina", red: "5G Satelital",
        focal: "f/1.56 Apertura Física OIS", sensor: "Samsung ISOCELL HPE (200 Mpx)", cpu_cores: "8 Núcleos MediaTek de 4nm Flagship", ufs: "UFS 4.0 Ultra Speed", giroscopio: "Físico Giro-Avanzado", refrigeracion: "Estructura de enfriamiento aeroespacial de Silicio-Carbono",
        highlights: ["✔ Increíble batería de 7000 mAh de Silicio-Carbono en un cuerpo ultradelgado de 7.9mm.", "✔ Sensor de 200 MP ISOCELL HPE + Teleobjetivo JN5 50MP, superando rotundamente a la competencia.", "✔ Pantalla extrema con 4500 Nits de brillo máximo y protección superior Gorilla Glass Victus."]
    }
};

// 3. BASE DE DATOS DE MARCAS COMPETIDORAS CON SUS 7 MODELOS COMPLETOS CADA UNA
const competitorsDatabase = {
    'samsung': {
        brandName: "Samsung", mascot: "infinixvssamsung1.jpg", mascotName: "SAMSUNG-ALIYE",
        brandColor: { border: 'border-blue-600', text: 'text-blue-500', glow: 'shadow-[0_0_30px_rgba(37,99,235,0.3)]', bg: 'bg-blue-600/20', rawColor: '#2563eb', badgeClass: 'bg-blue-600/20 text-blue-400 border border-blue-500/30' },
        models: {
            'a07': { name: "Samsung A07", image: "./A07.png", emoji: "📱", screen: "6.7\" PLS LCD (90 Hz)", screentype: "PLS LCD", hz: 90, processor: "Helio G99", ram: "4/6 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 8 Mpx", charge: "25W", battery: "5000 mAh", red: "4G", durability: "Plástico con empaque estándar", focal: "f/1.8", sensor: "Básico", cpu_cores: "8 Núcleos", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Pasiva sin láminas", highlights: ["✘ Pantalla PLS LCD estándar de solo 90Hz.", "✘ Velocidad de carga limitada a 25W.", "✘ Chasis básico de plástico propenso a fisuras por caídas."] },
            'a17': { name: "Samsung A17", image: "./A17.png", emoji: "📱", screen: "6.7\" PLS LCD (90 Hz)", screentype: "PLS LCD", hz: 90, processor: "Helio G99", ram: "4/8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 13 Mpx", charge: "25W", battery: "5000 mAh", red: "4G/5G", durability: "Policarbonato estándar", focal: "f/1.8", sensor: "Básico", cpu_cores: "8 Núcleos", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Pasiva", highlights: ["✘ Pantalla de 90Hz frente a la suavidad de 120Hz de Infinix.", "✘ Carga convencional de 25W conectado al enchufe mucho más tiempo.", "✘ Estructura plástica vulnerable a golpes cotidianos."] },
            'a27': { name: "Samsung A27", image: "./A27.png", emoji: "📱", screen: "6.6\" Super AMOLED (120 Hz)", screentype: "Super AMOLED", hz: 120, processor: "Exynos 1330", ram: "6/8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 12 Mpx", charge: "25W", battery: "5000 mAh", red: "4G/5G", durability: "Protección intermedia estándar", focal: "f/1.8", sensor: "Samsung", cpu_cores: "8 Núcleos Exynos", ufs: "UFS 2.1", giroscopio: "Virtual", refrigeracion: "Lámina térmica simple", highlights: ["✘ Procesador Exynos con tendencia al sobrecalentamiento bajo uso rudo.", "✘ Batería de solo 5000 mAh y carga anticuada de 25W.", "✘ Sin blindaje contra caídas certificada."] },
            'a37': { name: "Samsung A37", image: "./A37.png", emoji: "📱", screen: "6.6\" Super AMOLED (120 Hz)", screentype: "Super AMOLED", hz: 120, processor: "Exynos 1480", ram: "6/8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 12 Mpx", charge: "45W", battery: "5000 mAh", red: "5G", durability: "Plástico clásico", focal: "f/1.8", sensor: "Samsung", cpu_cores: "8 Núcleos Exynos", ufs: "UFS 2.2", giroscopio: "Físico", refrigeracion: "Pasiva", highlights: ["✘ Diagonal de pantalla inferior de 6.6 pulgadas.", "✘ Batería reducida de 5000 mAh frente a la autonomía Infinix.", "✘ Sin certificaciones de durabilidad contra impactos de alto impacto."] },
            'a57': { name: "Samsung A57", image: "./A57.png", emoji: "📱", screen: "6.6\" Super AMOLED (120 Hz)", screentype: "Super AMOLED", hz: 120, processor: "Exynos 1880", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 12 Mpx", charge: "45W", battery: "5000 mAh", red: "5G", durability: "Sellado regular IP54", focal: "f/1.8 OIS", sensor: "Sony", cpu_cores: "8 Núcleos Exynos High", ufs: "UFS 3.1", giroscopio: "Físico", refrigeracion: "Cámara de vapor pequeña", highlights: ["✘ Chip Exynos de rendimiento inestable en cargas de juego prolongadas.", "✘ Batería ajustada de 5000 mAh que exige recargas frecuentes.", "✘ Coste de marca elevado sin accesorios completos en su caja."] },
            's25fe': { name: "Samsung S25 FE", image: "./S25_FE.png", emoji: "📱", screen: "6.7\" Dynamic AMOLED 2X (120 Hz)", screentype: "Dynamic AMOLED", hz: 120, processor: "Exynos 2400", ram: "8/12 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 10 Mpx", charge: "25W", battery: "4500 mAh", red: "5G", durability: "IP68 convencional", focal: "f/1.8", sensor: "Samsung Premium", cpu_cores: "10 Núcleos Exynos", ufs: "UFS 3.1", giroscopio: "Físico", refrigeracion: "Cámara de vapor regular", highlights: ["✘ Batería sumamente pequeña de apenas 4500 mAh.", "✘ Carga obsoleta de 25W para su elevado rango de costo.", "✘ No cuenta con la durabilidad de caídas certificada por SGS."] },
            's26-plus': { name: "Galaxy S26+", image: "./S26+.png", emoji: "📱", screen: "6.7\" Dynamic AMOLED 2X QHD+ (120 Hz)", screentype: "Dynamic AMOLED 2X", hz: 120, processor: "Exynos 2600 / Snap 8 Elite", ram: "12 GB", storage: "256/512 GB", camera: "Trasera: 50 Mpx / Frontal: 12 Mpx", charge: "45W", battery: "4900 mAh", red: "5G", durability: "Armor Aluminum 2, IP68", focal: "f/1.8 OIS", sensor: "ISOCELL Samsung", cpu_cores: "8 Núcleos Alta gama", ufs: "UFS 4.0", giroscopio: "Físico Premium", refrigeracion: "Cámara de vapor VC avanzada", highlights: ["✘ Batería pequeña de 4900 mAh que reduce drásticamente el tiempo de pantalla.", "✘ La carga inalámbrica inversa es de apenas 4.5W (Infinix ofrece 10W directos por cable en serie Ultra).", "✘ No se puede expandir almacenamiento interno con tarjeta MicroSD."] }
        }
    },
    'honor': {
        brandName: "Honor", mascot: "infinixvshonor1.png", mascotName: "HONOR-TIBURÓN",
        brandColor: { border: 'border-purple-600', text: 'text-purple-400', glow: 'shadow-[0_0_30px_rgba(147,51,234,0.3)]', bg: 'bg-purple-600/20', rawColor: '#9333ea', badgeClass: 'bg-purple-600/20 text-purple-400 border border-purple-500/30' },
        models: {
            'x5c': { name: "Honor X5C", image: "./Honor_X5C.png", emoji: "📱", screen: "6.56\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Helio G81", ram: "4 GB", storage: "128 / 256 GB", camera: "Trasera: 50 Mpx / Frontal: 5 Mpx", charge: "15W", battery: "5260 mAh", red: "4G", durability: "Plástico convencional", focal: "f/1.8", sensor: "OmniVision", cpu_cores: "8 Núcleos", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Ninguna", highlights: ["✘ Monitor lento de 90Hz con resolución de entrada.", "✘ Velocidad de carga lenta de tan solo 15W.", "✘ Sensor de selfie de resolución muy recortada (5 Mpx)."] },
            'x7d': { name: "Honor X7D", image: "./Honor_x7d.png", emoji: "📱", screen: "6.7\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Snapdragon 685", ram: "6 / 8 GB", storage: "256 GB", camera: "Trasera: 108 Mpx / Frontal: 8 Mpx", charge: "35W", battery: "6500 mAh", red: "4G", durability: "Policarbonato estándar", focal: "f/1.75", sensor: "Samsung", cpu_cores: "8 Núcleos Snapdragon", ufs: "UFS 2.1", giroscopio: "Virtual", refrigeracion: "Pasiva térmica", highlights: ["✘ Tasa de actualización estándar de 90Hz sin fluidez extrema.", "✘ Snapdragon 685 de rendimiento gráfico modesto en juegos 3D.", "✘ Sin empaques protectores ni certificaciones contra caídas."] },
            'x8d': { name: "Honor X8D", image: "./honor_x8d.png", emoji: "📱", screen: "6.7\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 120, processor: "Snapdragon 6s Gen 2", ram: "8 GB", storage: "256/512 GB", camera: "Trasera: 108 Mpx / Frontal: 16 Mpx", charge: "45W", battery: "7000 mAh", red: "4G", durability: "Carcasa plástica estándar", focal: "f/1.75", sensor: "Samsung", cpu_cores: "8 Núcleos Qualcomm", ufs: "UFS 2.2", giroscopio: "Virtual", refrigeracion: "Lámina de grafito", highlights: ["✘ Chip Snapdragon 6s Gen 2 con tendencia a ralentizarse en juegos pesados.", "✘ Dispositivo grueso e incómodo en la mano debido a su gran grosor.", "✘ Chasis estándar que se raya y abolla con caídas cotidianas."] },
            '400-smart': { name: "Honor 400 Smart", image: "./Honor_400_smart.png", emoji: "📱", screen: "6.7\" TFT LCD (90 Hz)", screentype: "TFT LCD", hz: 90, processor: "Snapdragon 6s Gen 3", ram: "6 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 5 Mpx", charge: "35W", battery: "6500 mAh", red: "4G", durability: "Policarbonato estándar", focal: "f/1.8", sensor: "Básico", cpu_cores: "8 Núcleos Qualcomm", ufs: "UFS 2.1", giroscopio: "Virtual", refrigeracion: "Pasiva", highlights: ["✘ Pantalla TFT LCD con inferiores amigos de visión que IPS o AMOLED.", "✘ Memoria RAM física de 6 GB fija sin optimización dinámica.", "✘ Cámara selfie limitada a 5 Mpx para videollamadas."] },
            'magic-7-lite': { name: "Honor Magic 7 Lite", image: "./Honor_Magic_7_lite.png", emoji: "📱", screen: "6.78\" AMOLED (120 Hz)", screentype: "AMOLED", hz: 120, processor: "Snapdragon 6 Gen 1", ram: "8 GB", storage: "256/512 GB", camera: "Trasera: 108 Mpx / Frontal: 16 Mpx", charge: "66W", battery: "6600 mAh", red: "5G", durability: "Estructura convencional de vidrio", focal: "f/1.75 Curved", sensor: "Samsung Matrix", cpu_cores: "8 Núcleos Mid-Range", ufs: "UFS 2.2", giroscopio: "Físico", refrigeracion: "Estructura interna térmica simple", highlights: ["✘ Chipset Snapdragon 6 Gen 1 con baja tasa de fotogramas por segundo.", "✘ Sistema de audio mono deficiente en volumen máximo.", "✘ Pantalla curva expuesta a quebraduras por impactos accidentales."] },
            'magic-8-lite': { name: "Honor Magic 8 Lite", image: "./Honor_magic_8_lite.png", emoji: "📱", screen: "6.78\" AMOLED (120 Hz)", screentype: "AMOLED", hz: 120, processor: "Snapdragon 6 Gen 4", ram: "8/12 GB", storage: "256/512 GB", camera: "Trasera: 108 Mpx / Frontal: 16 Mpx", charge: "66 W", battery: "7500 mAh", red: "5G", durability: "Estructura convencional", focal: "f/1.75", sensor: "Matrix Samsung", cpu_cores: "8 Núcleos Qualcomm new", ufs: "UFS 2.2", giroscopio: "Físico", refrigeracion: "Grosor térmico pasivo", highlights: ["✘ Grosor y peso incrementados en mano por su batería robusta.", "✘ Carga de 66W que tarda bastante en llenar su inmensa batería.", "✘ Sin empaques especiales ni blindajes certificados contra caídas."] },
            '600': { name: "Honor 600", image: "./Honor_600.png", emoji: "📱", screen: "6.78\" AMOLED (120 Hz)", screentype: "AMOLED", hz: 120, processor: "Snapdragon 7 Gen 4", ram: "8/12 GB", storage: "256/512 GB", camera: "Trasera: 200 Mpx / Frontal: 50 Mpx", charge: "80W", battery: "7000 mAh", red: "5G", durability: "Construcción de plástico", focal: "f/1.6", sensor: "Samsung High Mega", cpu_cores: "8 Núcleos Snapdragon High", ufs: "UFS 3.1", giroscopio: "Físico", refrigeracion: "Cámara de vapor mediana", highlights: ["✘ Dispositivo excesivamente robusto y pesado de manejar en el bolsillo.", "✘ Fotos masivas de 200 Mpx que saturan y llenan la memoria interna de inmediato.", "✘ Sin certificaciones anticaídas de grado militar real."] }
        }
    },
    'motorola': {
        brandName: "Motorola", mascot: "infinixvsmotorola1.png", mascotName: "MOTOROLA-BAT",
        brandColor: { border: 'border-slate-300/80', text: 'text-slate-200', glow: 'shadow-[0_0_30px_rgba(255,255,255,0.15)]', bg: 'bg-white/10', rawColor: '#ffffff', badgeClass: 'bg-white/15 text-white border border-white/20' },
        models: {
            'g06': { name: "Motorola G06", image: "./G06.png", emoji: "📱", screen: "6.56\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Helio G81", ram: "4 GB", storage: "128 GB", camera: "Trasera: 15 Mpx / Frontal: 6 Mpx", charge: "10W", battery: "5500 mAh", red: "4G", durability: "Resistencia básica contra humedad", focal: "f/2.2", sensor: "OmniVision", cpu_cores: "8 Núcleos", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Ninguna", highlights: ["✘ Procesador Helio G81 básico propenso a tirones frecuentes.", "✘ Velocidad de carga extremadamente lenta de solo 10W.", "✘ Cámaras de baja resolución (15 Mpx traseros y 6 Mpx frontal)."] },
            'g15': { name: "Motorola G15", image: "./G15.PNG", emoji: "📱", screen: "6.5\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Helio G81", ram: "4 GB", storage: "256 / 512 GB", camera: "Trasera: 50 Mpx / Frontal: 8 Mpx", charge: "18W", battery: "5200 mAh", red: "4G", durability: "Policarbonato simple", focal: "f/1.8", sensor: "Básico", cpu_cores: "8 Núcleos", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Pasiva", highlights: ["✘ Pantalla compacta y desactualizada a solo 90Hz de refresco.", "✘ Carga de tan solo 18W, tarda más de dos horas en llenarse.", "✘ Helio G81 con rendimiento limitado para tareas de juego exigentes."] },
            'g56': { name: "Motorola G56", image: "./G56.png", emoji: "📱", screen: "6.5\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 120, processor: "Dimensity 7060", ram: "8 GB", storage: "256 / 512 GB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "33W", battery: "5200 mAh", red: "5G", durability: "Resistencia a salpicaduras estándar", focal: "f/1.8", sensor: "OmniVision High", cpu_cores: "8 Núcleos MediaTek", ufs: "UFS 2.2", giroscopio: "Virtual", refrigeracion: "Lámina térmica simple", highlights: ["✘ Pantalla muy compacta de 6.5 pulgadas con bordes gruesos.", "✘ Carga media de 33W superada por nuestros watts en Infinix.", "✘ No cuenta con la durabilidad probada ante impactos de grado militar."] },
            'g67': { name: "Motorola G67", image: "./G67.png", emoji: "📱", screen: "6.5\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 120, processor: "Dimensity 6300", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "33W", battery: "5200 mAh", red: "5G", durability: "Resistencia estándar", focal: "f/1.8", sensor: "Básico MediaTek", cpu_cores: "8 Núcleos", ufs: "UFS 2.1", giroscopio: "Virtual", refrigeracion: "Pasiva", highlights: ["✘ Velocidad de carga lenta de 33W en su rango de competencia.", "✘ Procesador Dimensity 6300 con frecuencias recortadas de rendimiento.", "✘ Diagonal de pantalla compacta de 6.5\" que reduce la inmersión."] },
            'g86': { name: "Motorola G86", image: "./G86.png", emoji: "📱", screen: "6.6\" OLED (120 Hz)", screentype: "OLED", hz: 120, processor: "Dimensity 7300", ram: "8 GB", storage: "256 / 512 GB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "33W", battery: "5200 mAh", red: "5G", durability: "Protección contra salpicaduras ligera", focal: "f/1.8 OIS", sensor: "Sony IMX", cpu_cores: "8 Núcleos MediaTek Custom", ufs: "UFS 2.2", giroscopio: "Físico", refrigeracion: "Lámina de grafito", highlights: ["✘ Carga lenta de 33W que frena tu ritmo diario.", "✘ No tiene empaques internos de blindaje militar contra caídas duras.", "✘ Sonido mono básico con menor respuesta acústica."] },
            'edge-50-fusion': { name: "Motorola Edge 50 Fusion", image: "./Edge_50_Fusion.png", emoji: "📱", screen: "6.7\" P-OLED (144 Hz)", screentype: "P-OLED Curva", hz: 144, processor: "Snapdragon 6 Gen 1", ram: "8 / 12 GB", storage: "256 / 512 GB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "68W", battery: "5000 mAh", red: "5G", durability: "IP68 estándar", focal: "f/1.8 Curved", sensor: "Sony LYTIA LYT-700C", cpu_cores: "8 Núcleos Mid-Qualcomm", ufs: "UFS 2.2", giroscopio: "Físico", refrigeracion: "Disipación interna estándar de grafito", highlights: ["✘ Procesador Snapdragon 6 Gen 1 básico para juegos de alta exigencia.", "✘ Pantalla curva sumamente expuesta a romperse con facilidad.", "✘ Sin ranura para expandir memoria MicroSD dedicada."] },
            'edge-60-fusion': { name: "Motorola Edge 60 Fusion", image: "./Edge_60_Fusion.png", emoji: "📱", screen: "6.7\" P-OLED (144 Hz)", screentype: "P-OLED Curva", hz: 144, processor: "Dimensity 7300", ram: "8 / 12 GB", storage: "256 / 512 GB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "68W", battery: "5200 mAh", red: "5G", durability: "IP68 estándar", focal: "f/1.8", sensor: "Sony LYTIA", cpu_cores: "8 Núcleos MediaTek 4nm", ufs: "UFS 2.2", giroscopio: "Físico", refrigeracion: "Lámina térmica simple", highlights: ["✘ Batería reducida a solo 5200 mAh frente a gigantes de Infinix.", "✘ No permite expandir tu almacenamiento por medio de tarjetas MicroSD.", "✘ Pantalla curva vulnerable a caídas accidentales costosas de reparar."] },
            'edge-70-fusion': { name: "Motorola Edge 70 Fusion", image: "./Edge_70_Fusion.png", emoji: "📱", screen: "6.7\" P-OLED (144 Hz)", screentype: "P-OLED Curva", hz: 144, processor: "Snapdragon 7s Gen 3", ram: "8/12 GB", storage: "256 / 512 GB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "68W", battery: "7000 mAh", red: "5G", durability: "IP68 estándar", focal: "f/1.8", sensor: "Sony Premium sensor", cpu_cores: "8 Núcleos Qualcomm", ufs: "UFS 3.1", giroscopio: "Físico", refrigeracion: "Térmica pasiva robusta", highlights: ["✘ Grosor excesivo y pesadez en el manejo diario debido a sus 7000 mAh.", "✘ Pantalla curva expuesta a quebraduras por impactos accidentales.", "✘ Ausencia de bandeja física de expansión para tarjeta MicroSD."] }
        }
    },
    'realme': {
        brandName: "Realme", mascot: "infinixvsrealme1.png", mascotName: "REALME-GATO",
        brandColor: { border: 'border-yellow-500', text: 'text-yellow-500', glow: 'shadow-[0_0_30px_rgba(234,179,8,0.3)]', bg: 'bg-yellow-500/20', rawColor: '#eab308', badgeClass: 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30' },
        models: {
            '15': { name: "Realme 15", image: "./Realme_15.png", emoji: "📱", screen: "6.72\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 120, processor: "Dimensity 7300", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 50 Mpx", charge: "45W", battery: "6500 mAh", red: "5G", durability: "Cuerpo plástico convencional", focal: "f/1.8", sensor: "Samsung", cpu_cores: "8  Núcleos", ufs: "UFS 2.2", giroscopio: "Virtual", refrigeracion: "Grafito", highlights: ["✘ Grosor y pesadez física que cansa la mano en uso continuo.", "✘ Chasis estándar que se marca y daña rápidamente ante golpes.", "✘ Bloatware excesivo en la capa de personalización de software."] },
            '15t': { name: "Realme 15T", image: "./REALME_15T.png", emoji: "📱", screen: "6.7\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 120, processor: "Dimensity 6400", ram: "8/12 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 50 Mpx", charge: "45W", battery: "6550 mAh", red: "5G", durability: "Estructura de plástico estándar", focal: "f/1.8", sensor: "Samsung", cpu_cores: "8 Núcleos", ufs: "UFS 2.2", giroscopio: "Virtual", refrigeracion: "Pasiva térmica", highlights: ["✘ Procesador Dimensity 6400 con menor desempeño que nuestros chips Note.", "✘ Elevada temperatura posterior bajo largas sesiones de juegos.", "✘ Sin certificaciones rigurosas anticaídas militar."] },
            '15t-pro': { name: "Realme 15T PRO", image: "./Realme_15_Pro.png", emoji: "📱", screen: "6.7\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 120, processor: "Dimensity 7300", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 50 Mpx", charge: "80W", battery: "8000 mAh", red: "5G", durability: "Chasis convencional pesado", focal: "f/1.8", sensor: "Sony IMX", cpu_cores: "8 Núcleos MediaTek", ufs: "UFS 2.2", giroscopio: "Virtual", refrigeracion: "Lámina simple", highlights: ["✘ Peso sumamente elevado en mano por su enorme batería de 8000 mAh.", "✘ No tiene ranura dedicada de MicroSD.", "✘ Sin certificaciones de alta resistencia ante caídas."] },
            'c100': { name: "Realme C100", image: "./realme_C100.png", emoji: "📱", screen: "6.72\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Helio G92", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 8 Mpx", charge: "45W", battery: "8000 mAh", red: "4G", durability: "Carcasa plástica básica", focal: "f/1.8", sensor: "OmniVision", cpu_cores: "8 Núcleos", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Ninguna", highlights: ["✘ Tasa de refresco obsoleta de 90Hz.", "✘ Dispositivo excesivamente pesado en bolsillo por su volumen físico.", "✘ Procesador Helio G92 propenso a ralentizaciones en multitarea."] },
            'c100x': { name: "Realme C100x", image: "./realme_C100X.png", emoji: "📱", screen: "6.7\" TFT LCD (90 Hz)", screentype: "TFT LCD", hz: 90, processor: "Unisoc T615", ram: "4 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 5 Mpx", charge: "45W", battery: "8000 mAh", red: "4G", durability: "Plástico convencional", focal: "f/1.8", sensor: "Básico", cpu_cores: "8 Núcleos Unisoc", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Pasiva", highlights: ["✘ Pantalla TFT LCD con inferiores ángulos de visión y colores opacos.", "✘ Procesador Unisoc T615 de gama de entrada muy básico.", "✘ Cámara selfie de muy baja fidelidad (5 Mpx)."] },
            'c100i': { name: "Realme C100i", image: "./realme_C100i.png", emoji: "📱", screen: "6.7\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Unisoc T615", ram: "4 GB", storage: "128 GB", camera: "Trasera: 8 Mpx / Frontal: 5 Mpx", charge: "15W", battery: "6000 mAh", red: "4G", durability: "Cuerpo plástico simple", focal: "f/2.0", sensor: "Básico entrada", cpu_cores: "8 Núcleos Unisoc", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Ninguna", highlights: ["✘ Almacenamiento limitado de solo 128 GB.", "✘ Cámara principal de muy baja definición de 8 Mpx.", "✘ Carga sumamente lenta de 15W."] }
        }
    },
    'oppo': {
        brandName: "OPPO", mascot: "infinixvsoppo1.png", mascotName: "OPPO-OLLIE",
        brandColor: { border: 'border-red-600', text: 'text-red-500', glow: 'shadow-[0_0_30px_rgba(220,38,38,0.3)]', bg: 'bg-red-600/20', rawColor: '#dc2626', badgeClass: 'bg-red-600/20 text-red-400 border border-red-500/30' },
        models: {
            'a6': { name: "OPPO A6", image: "./OPPO_A6.png", emoji: "📱", screen: "6.67\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Snapdragon 685", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 8 Mpx", charge: "45W", battery: "7000 mAh", red: "4G", durability: "Plástico convencional", focal: "f/1.8", sensor: "Samsung", cpu_cores: "8 Núcleos Qualcomm", ufs: "UFS 2.1", giroscopio: "Virtual", refrigeracion: "Lámina térmica pasiva", highlights: ["✘ Pantalla de tan solo 90Hz con panel convencional.", "✘ Procesamiento moderado bajo el procesador Snapdragon 685.", "✘ Chasis sumamente grueso y pesado por su volumen físico."] },
            'a6c': { name: "OPPO A6c", image: "./OPPO_A6c.png", emoji: "📱", screen: "6.75\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Unisoc T7250", ram: "4GB", storage: "128 GB", camera: "Trasera: 13 Mpx / Frontal: 5 Mpx", charge: "N/A", battery: "6600 mAh", red: "4G", durability: "Cuerpo de plástico convencional", focal: "f/2.2", sensor: "Básico", cpu_cores: "8 Núcleos Unisoc", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Ninguna", highlights: ["✘ No cuenta con sistema de carga rápida especificado (N/A).", "✘ Almacenamiento recortado de 128 GB y 4GB de RAM.", "✘ Cámara trasera básica de 13 Mpx con bajo nivel de detalle."] },
            'a6k': { name: "OPPO A6k", image: "./OPPO_A6k.png", emoji: "📱", screen: "6.67\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Snapdragon 685", ram: "4 GB", storage: "128 GB", camera: "Trasera: 50 Mpx / Frontal: 50 Mpx", charge: "45W", battery: "6500 mAh", red: "4G", durability: "Protección intermedia básica", focal: "f/1.8", sensor: "Samsung", cpu_cores: "8 Núcleos Qualcomm", ufs: "UFS 2.1", giroscopio: "Virtual", refrigeracion: "Pasiva", highlights: ["✘ Pantalla de 90Hz que carece de la fluidez óptima de Infinix.", "✘ Memoria RAM física de solo 4 GB que limita la multitarea pesada.", "✘ Sin certificaciones militares válidas contra caídas."] },
            'a6-pro': { name: "OPPO A6 Pro 5g", image: "./OPPO_A6_Pro.png", emoji: "📱", screen: "6.67\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 120, processor: "Dimensity 6300", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 16 Mpx", charge: "88 W", battery: "65000 mAh", red: "5G", durability: "Chasis convencional estándar", focal: "f/1.8", sensor: "Sony IMX", cpu_cores: "8  Núcleos MediaTek", ufs: "UFS 2.2", giroscopio: "Virtual", refrigeracion: "Lámina simple", highlights: ["✘ Procesador Dimensity 6300 con núcleos de frecuencia reducida.", "✘ Formato de peso sumamente desequilibrado en mano.", "✘ Sin blindaje anticaídas probado SGS 5 estrellas."] },
            'reno14f': { name: "OPPO Reno 14F", image: "./OPPO_Reno_14F.png", emoji: "📱", screen: "6.67\" AMOLED (120 Hz)", screentype: "AMOLED", hz: 120, processor: "Snapdragon 6Gen1", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 16 Mpx", charge: "88 W", battery: "65000 mAh", red: "5G", durability: "Estructura convencional de vidrio", focal: "f/1.8", sensor: "Sony LYTIA", cpu_cores: "8 Núcleos Mid-Qualcomm", ufs: "UFS 2.2", giroscopio: "Físico", refrigeracion: "Térmica interna regular", highlights: ["✘ Procesador Snapdragon 6 Gen 1 básico para su gama de costo.", "✘ Ausencia de bandeja dedicada para expansión de MicroSD.", "✘ Vulnerabilidad física ante caídas accidentales."] },
            'reno14': { name: "OPPO Reno 14", image: "./OPPO_Reno_14.png", emoji: "📱", screen: "6.7\" AMOLED (120 Hz)", screentype: "AMOLED", hz: 120, processor: "Dimensity 8350", ram: "8/12 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 50 Mpx", charge: "80W", battery: "6000 mAh", red: "5G", durability: "IP64 protección estándar", focal: "f/1.8 OIS", sensor: "Sony Premium Custom", cpu_cores: "8 Núcleos MediaTek High", ufs: "UFS 3.1", giroscopio: "Físico", refrigeracion: "Cámara de vapor VC regular", highlights: ["✘ Almacenamiento limitado fijo de 256 GB sin ranura de MicroSD.", "✘ No tiene empaques de amortiguación militar en esquinas.", "✘ Audio mono propenso a saturación en volúmenes altos."] }
        }
    },
    'tecno': {
        brandName: "Tecno", mascot: "infinixvstecno1.png", mascotName: "TECNO-ROBOT",
        brandColor: { border: 'border-sky-400', text: 'text-sky-400', glow: 'shadow-[0_0_30px_rgba(56,189,248,0.25)]', bg: 'bg-sky-400/20', rawColor: '#38bdf8', badgeClass: 'bg-sky-400/20 text-sky-400 border border-sky-400/30' },
        models: {
            'sparkgo3': { name: "Tecno Spark GO3", image: "./TECNO_GO3.PNG", emoji: "📱", screen: "6.6\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Unisoc T7250", ram: "4 GB", storage: "128 GB", camera: "Trasera: 13 Mpx / Frontal: 8 Mpx", charge: "15W", battery: "5000 mAh", red: "4G", durability: "Plástico básico", focal: "f/2.2", sensor: "Básico", cpu_cores: "8 Núcleos Unisoc", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Ninguna", highlights: ["✘ Procesador Unisoc T7250 muy limitado en operaciones pesadas.", "✘ Pantalla lenta de 90Hz con resolución de entrada.", "✘ Velocidad de carga lenta de tan solo 15W."] },
            'spark50': { name: "Tecno Spark 50", image: "./spark_50.png", emoji: "📱", screen: "6.6\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Helio G81", ram: "4/8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 8 Mpx", charge: "18w", battery: "7000 mAh", red: "4G", durability: "Carcasa plástica estándar", focal: "f/1.8", sensor: "Básico", cpu_cores: "8 Núcleos", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Pasiva", highlights: ["✘ Procesador Helio G81 de bajo rendimiento.", "✘ Tasa de refresco baja de 90Hz en pantalla de tamaño compacto.", "✘ Carga de solo 18W, tarda horas en llenar sus 7000 mAh."] },
            'spark50-5g': { name: "Tecno Spark 50 5G", image: "./spark_50_5G.png", emoji: "📱", screen: "6.6\" IPS LCD (120 Hz)", screentype: "IPS LCD", hz: 120, processor: "Dimensity 6400", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 8 Mpx", charge: "45 W", battery: "6500 mAh", red: "5G", durability: "Policarbonato de alta densidad", focal: "f/1.8", sensor: "OmniVision", cpu_cores: "8 Núcleos MediaTek", ufs: "UFS 2.2", giroscopio: "Virtual", refrigeracion: "Lámina térmica pasiva", highlights: ["✘ Carece del brillo y colores de la tecnología AMOLED.", "✘ Sensor frontal recortado a solo 8 Mpx.", "✘ Sin pruebas rigurosas certificadas contra caídas de 5 estrellas."] },
            'camon50': { name: "Tecno Camon 50", image: "./CAMON_50.PNG", emoji: "📱", screen: "6.78\" AMOLED (120 Hz)", screentype: "AMOLED", hz: 120, processor: "Helio G200 Ultimate", ram: "8/12 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "45W", battery: "6500 mAh", red: "4G", durability: "IP53 resistencia de entrada", focal: "f/1.7", sensor: "Samsung ISOCELL", cpu_cores: "8 Núcleos", ufs: "UFS 2.2", giroscopio: "Virtual", refrigeracion: "Lámina de grafito", highlights: ["✘ No tiene chasis blindado de protección militar.", "✘ Conectividad reducida a redes móviles de 4G.", "✘ Software con excesivas aplicaciones preinstaladas molestas."] },
            'pova-curve-2': { name: "Tecno Pova Curve 2", image: "./POVA_CURVE.PNG", emoji: "📱", screen: "6.78\" AMOLED Curva (120 Hz)", screentype: "AMOLED Curva", hz: 120, processor: "Dimensity 7100", ram: "8GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 13 Mpx", charge: "45W", battery: "8000 mAh", red: "5G", durability: "IP54 protección media", focal: "f/1.8 Curved", sensor: "Sony IMX", cpu_cores: "8 Núcleos MediaTek", ufs: "UFS 2.2", giroscopio: "Físico", refrigeracion: "Térmica integrada interna", highlights: ["✘ Dispositivo excesivamente robusto y pesado debido a sus 8000 mAh.", "✘ Pantalla curva vulnerable a roturas accidentales y caídas laterales.", "✘ Falta de ranura de expansión MicroSD dedicada."] }
        }
    },
    'xiaomi': {
        brandName: "Xiaomi", mascot: "infinix vs Xioami.png", mascotName: "XIAOMI-MITU",
        brandColor: { border: 'border-orange-500', text: 'text-orange-500', glow: 'shadow-[0_0_30px_rgba(249,115,22,0.25)]', bg: 'bg-orange-500/20', rawColor: '#f97316', badgeClass: 'bg-orange-500/20 text-orange-400 border border-orange-500/30' },
        models: {
            'redmi15': { name: "Redmi 15", image: "./REDMI_15.png", emoji: "📱", screen: "6.7\" IPS LCD (90 Hz)", screentype: "IPS LCD", hz: 90, processor: "Snapdragon 685", ram: "8 GB", storage: "256 GB", camera: "Trasera: 50 Mpx / Frontal: 8 Mpx", charge: "33W", battery: "7000 mAh", red: "4G", durability: "Cuerpo plástico simple", focal: "f/1.8", sensor: "Básico", cpu_cores: "8 Núcleos Qualcomm", ufs: "eMMC 5.1", giroscopio: "Virtual", refrigeracion: "Pasiva", highlights: ["✘ Pantalla lenta de 90Hz con panel básico.", "✘ Tarda horas conectado al cargador de 33W por su batería de 7000 mAh.", "✘ Chipset Snapdragon 685 de rendimiento modesto en gráficos."] },
            'note15': { name: "Redmi Note 15", image: "./REDMI_NOTE_15.png", emoji: "📱", screen: "6.67\" AMOLED (120 Hz)", screentype: "AMOLED", hz: 120, processor: "Helio G100 / Snap 6 Gen 3", ram: "8 GB", storage: "256 GB", camera: "Trasera: 108 Mpx / Frontal: 20 Mpx", charge: "33W / 45W", battery: "6000 / 5520 mAh", red: "4G / 5G", durability: "IP54 estándar", focal: "f/1.75", sensor: "Samsung High Pixel", cpu_cores: "8 Núcleos Base", ufs: "UFS 2.2", giroscopio: "Virtual", refrigeracion: "Lámina térmica", highlights: ["✘ Diagonal de pantalla inferior de 6.67 pulgadas.", "✘ Chasis estándar vulnerable a abolladuras y rayones accidentales.", "✘ Sin blindaje certificado grado militar."] },
            'note15-pro': { name: "Redmi Note 15 Pro", image: "./REDMI_NOTE_15_PRO.png", emoji: "📱", screen: "6.67\" Super AMOLED (120 Hz)", screentype: "Super AMOLED", hz: 120, processor: "Helio G200 / Dim 7400", ram: "8 GB", storage: "256 GB", camera: "Trasera: 200 Mpx / Frontal: 32 Mpx", charge: "45W", battery: "6500 / 6580 mAh", red: "4G / 5G", durability: "IP54 estándar", focal: "f/1.65", sensor: "Samsung HPE sensor", cpu_cores: "8 Núcleos Mid", ufs: "UFS 2.2", giroscopio: "Físico", refrigeracion: "Pasiva con grafito", highlights: ["✘ Sensor de 200 Mpx que genera fotografías de tamaño masivo colapsando el almacenamiento.", "✘ Estructura curva tradicional sin amortiguación lateral.", "✘ Menor velocidad de carga comparado con Note 60 Pro de Infinix."] },
            'note15-pro-plus': { name: "Redmi Note 15 Pro +", image: "./REDMI_NOTE_15_PRO_PLUS.png", emoji: "📱", screen: "6.67\" Super AMOLED (120 Hz)", screentype: "Super AMOLED", hz: 120, processor: "Snapdragon 7S Gen 4", ram: "8/12 GB", storage: "256/512GB", camera: "Trasera: 200 Mpx / Frontal: 32 Mpx", charge: "100W", battery: "6500 mAh", red: "5G", durability: "IP68 estándar", focal: "f/1.65 OIS", sensor: "Samsung ISOCELL HPE", cpu_cores: "8 Núcleos Qualcomm Mid-High", ufs: "UFS 3.1", giroscopio: "Físico", refrigeracion: "Cámara de vapor regular", highlights: ["✘ Sensor fotográfico de 200 Mpx de procesamiento perezoso.", "✘ No tiene blindaje anticaídas de grado militar certificado.", "✘ Diagonal de pantalla más pequeña que la gama Note de Infinix."] },
            'xiaomi15': { name: "Xiaomi 15", image: "./XIAOMI_15.png", emoji: "📱", screen: "6.36\" LTPO OLED (120 Hz)", screentype: "LTPO OLED", hz: 120, processor: "Snapdragon 8 ELITE", ram: "12/16 GB", storage: "512 GB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "90W", battery: "5240 mAh", red: "5G", durability: "IP68 Avanzada", focal: "f/1.6 Leica", sensor: "OmniVision Custom Premium", cpu_cores: "8 Núcleos Flagship Qualcomm", ufs: "UFS 4.0", giroscopio: "Físico Premium", refrigeracion: "Sistema de enfriamiento líquido circular VC", highlights: ["✘ Diagonal de pantalla sumamente pequeña de 6.36 pulgadas.", "✘ Elevadísimo rango de precio fuera de la accesibilidad del mercado de masa.", "✘ Batería reducida a 5240 mAh frente a la gran autonomía de Infinix."] },
            'xiaomi17t': { name: "Xiaomi 17T", image: "./XIAOMI_17TT.png", emoji: "📱", screen: "6.59\" AMOLED 1.5K (120 Hz)", screentype: "AMOLED", hz: 120, processor: "Dimensity 8500-Ultra", ram: "12 GB", storage: "256/512 GB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "67W", battery: "6500 mAh", red: "5G", durability: "IP68, Gorilla Glass 7i", focal: "f/1.7", sensor: "Sony IMX", cpu_cores: "8 Núcleos MediaTek High", ufs: "UFS 3.1", giroscopio: "Físico", refrigeracion: "Cámara de vapor VC líquida", highlights: ["✘ Almacenamiento no expandible mediante tarjeta microSD.", "✘ Carece de soporte para carga inalámbrica.", "✘ Tamaño de pantalla inferior (6.59\") frente a las 6.78\" del Note de Infinix."] },
            'xiaomi17t-pro': { name: "Xiaomi 17T Pro", image: "./XIAOMI_17T_Pro.png", emoji: "📱", screen: "6.83\" AMOLED 1.5K (144 Hz)", screentype: "AMOLED", hz: 144, processor: "Dimensity 9500", ram: "12/16 GB", storage: "256/1TB", camera: "Trasera: 50 Mpx / Frontal: 32 Mpx", charge: "100W", battery: "7000 mAh", red: "5G", durability: "IP68, Marco Aleación", focal: "f/1.6 OIS", sensor: "Sony Flagship", cpu_cores: "8 Núcleos Ultimate MediaTek", ufs: "UFS 4.0", giroscopio: "Físico Premium", refrigeracion: "Sistema VC avanzado de disipación circular", highlights: ["✘ Su carga inalámbrica inversa es de solo 5W, superada por los 10W directos del Note 60 Ultra.", "✘ No permite expandir la memoria interna vía MicroSD.", "✘ Su peso es elevado (219g) y su sensor principal de 50 MP no compite contra los 200 MP ISOCELL de Infinix."] }
        }
    }
};

// Guardar base de datos para exportación limpia en consola
window.baseDatosDispositivosInfinix = infinixDatabase;
window.baseDatosCompetidoresCompleta = competitorsDatabase;